### ISSUE TITLE
What does this software do?

### ISSUE THREAD

**Issue by TheOriginal92** [tatulea/FUSB302_ESP32#1]
Hey, i am looking for a way to control USB PD via an ESP32/8266.
Whats the intend of this software?

**Comment by tatulea** [comment]
Hi, I will add a README in about one hour. I was using the library from ON Semi (v4.1.1) and adapt their examples (ARM and PIC) to ESP.

**Comment by tatulea** [comment]
Please, have a look now.

**Comment by TheOriginal92** [comment]
Thank you very much :)
